AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { ignored_files: db/schema.rb}
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
#IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 3, ignored_files: [app/views/kaminari] }
MoveFinderToNamedScopeCheck: { }
# +2 over default to account for using ivars for translating flash messages
MoveModelLogicIntoModelCheck: { use_count: 10 }
# Temporary skip of routes.rb, to fix this causes breadcrumb messiness
NeedlessDeepNestingCheck: { nested_count: 2, ignored_files: [] }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: { except_methods: ["Users::SessionsController#respond_to_on_destroy", "Admin::NotificationsController#notification_params", "ApplicationController#after_sign_out_path_for", "PlotsController#create_params", "ApplianceRoomsController#appliance_room_params", "FinishRoomsController#finish_room_params", "Ckeditor::PicturesController#find_asset", "Ckeditor::PicturesController#authorize_resource", "Residents::InvitationsController#after_accept_path_for", "FinishesController#current_ability", "Residents::SessionsController#after_sign_in_path_for", "Users::SessionsController#after_sign_in_path_for", "Homeowners::BaseController#record_event"] }
RemoveUnusedMethodsInHelpersCheck: { except_methods: ["RoomsHelper#plot_rooms", "TabsHelper#initialize", "TabsHelper#active?", "TabsHelper#to_a", "TabsHelper#developer_tabs", "ApplicationHelper#sortable", "PhaseTabsHelper#phase_tabs"] }
RemoveUnusedMethodsInModelsCheck: { except_methods: ["Developer#prime_lettings_admin", "Division#prime_lettings_admin", "User#password_required?", "ApplicationRecord#to_str", "SendToAll#to_str", "Resident#plot_number", "*#rebuild_pg_search_documents", "Ckeditor::AttachmentFile#url_thumb", "Ckeditor::Picture#url_content", "Referral#delete_28_days_old", "Vaboo#check_expired_premium", "Developer#prime_lettings_admin","User#branch_administrator","Listing#admin_listings", "Crms::Document#rationalise_docs", "Crms::Resident#rationalise!", "Invitation#resident_invitation_summary", "PlotTimeline#reset", "Api::Tenant#send_devise_notification"] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { ignored_files: [app/views/components/_empty_list]}
#RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
#UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
