AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2, ignored_files: [app/views/kaminari] }
MoveFinderToNamedScopeCheck: { }
# +2 over default to account for using ivars for translating flash messages
MoveModelLogicIntoModelCheck: { use_count: 6 }
# Temporary skip of routes.rb, to fix this causes breadcrumb messiness
NeedlessDeepNestingCheck: { nested_count: 2, ignored_files: [] }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: { except_methods: ["Users::SessionsController#respond_to_on_destroy", "Admin::NotificationsController#notification_params", "ApplicationController#after_sign_out_path_for", "PlotsController#create_params", "ApplianceRoomsController#appliance_room_params", "FinishRoomsController#finish_room_params"] }
RemoveUnusedMethodsInHelpersCheck: { except_methods: ["TabsHelper#initialize", "TabsHelper#active?", "TabsHelper#to_a", "TabsHelper#developer_tabs", "ApplicationHelper#sortable", "PhaseTabsHelper#phase_tabs"] }
RemoveUnusedMethodsInModelsCheck: { except_methods: ["User#password_required?", "ApplicationRecord#to_str", "SendToAll#to_str", "Resident#plot_number", "*#rebuild_pg_search_documents"] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
